import { Montserrat} from "next/font/google";
import "./globals.css";
import Nav from "./nav";


const mon = Montserrat({
  variable: "--font-mont",
  subsets: ["latin"],
  weight:["100","200","300","400"]
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${mon.variable} antialiased`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
